SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER TR_Seguridad
ON database
FOR DROP_TABLE
AS
BEGIN
RAISERROR ('No está permitido borrar  tablas !' , 16, 1)
ROLLBACK TRANSACTION
END
GO
DISABLE TRIGGER TR_Seguridad ON DATABASE
GO
